name = "Piko"
license = "MIT"
licenselink = "https://faithportfolio.pages.dev/"
description = "Piko is a minimalistic and fast theme powered by Hugo for building a blog or portfolio."
homepage = "https://faithportfolio.pages.dev/"
demosite = "https://faithportfolio.pages.dev/"
tags = ['forestry', 'landing-page', 'fast', 'light', 'dark', 'modern', 'heksagon', 'personal', 'dark mode', 'picco', 'blog', 'responsive', 'clean', 'simple', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages', 'resume', 'portfolio', 'google analytics', 'customizable', 'search', 'presentation', 'product', 'theme', 'company', 'archive']
features = ['picco','responsive']
min_version = "0.91.0"

[author]
  name = "Heksagon"
  homepage = "http://www.heksagon.net/"
